"""ProductCodes created

Revision ID: 2a3de651c8c1
Revises: 371f97071b82
Create Date: 2025-05-15 00:50:32.424033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3de651c8c1'
down_revision: Union[str, None] = '371f97071b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_codes'))
    )
    op.create_index(op.f('ix_product_codes_code'), 'product_codes', ['code'], unique=True)
    op.create_table('user_product_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_code_id'], ['product_codes.id'], name=op.f('fk_user_product_association_product_code_id_product_codes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_product_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'product_code_id', name=op.f('pk_user_product_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product_association')
    op.drop_index(op.f('ix_product_codes_code'), table_name='product_codes')
    op.drop_table('product_codes')
    # ### end Alembic commands ###
