"""add cascade

Revision ID: fd5cf21b4483
Revises: 2a3de651c8c1
Create Date: 2025-05-27 20:46:56.797582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5cf21b4483'
down_revision: Union[str, None] = '2a3de651c8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_product_association_user_id_users', 'user_product_association', type_='foreignkey')
    op.drop_constraint('fk_user_product_association_product_code_id_product_codes', 'user_product_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_product_association_user_id_users'), 'user_product_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_product_association_product_code_id_product_codes'), 'user_product_association', 'product_codes', ['product_code_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_product_association_product_code_id_product_codes'), 'user_product_association', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_product_association_user_id_users'), 'user_product_association', type_='foreignkey')
    op.create_foreign_key('fk_user_product_association_product_code_id_product_codes', 'user_product_association', 'product_codes', ['product_code_id'], ['id'])
    op.create_foreign_key('fk_user_product_association_user_id_users', 'user_product_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
